name: Terraform CI/CD with GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
      branches:
         - main
jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Appy
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
    
            
        
      
